language: php

php:
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

  fast_finish: true

  include:
    - php: 5.6
      env:
        - COVERALLS=1

  fast_finish: true

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

script:
  - phpunit
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php bin/coveralls -c .coveralls.yml -v; fi"

notifications:
  slack: world-architects:CEb47sLB0YiVywpTXvRzR9Vc
  email: true
  recipients:
        - travis-ci@world-architects.com
